kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: node:18
    commands:
      - npm install
      - echo "Tests passed"

  - name: build_and_push
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: vaishanvi1234/demo-app-29
      tags:
        - latest
